apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  namespace: default
  labels:
    app: pod-netology
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
    - containerPort: 8443
