apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local
spec:
  storageClassName: manual
  capacity:
    storage: 150Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /storage/pv-local
