apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-multitool-v2
  labels:
    app: task1-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task1-4
  template:
    metadata:
      labels:
        app: task1-4
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: configmap-nginx-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        env:
        - name: NGINX_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-nginx
              key: nginx-http-port
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-mutlitool
              key: multitool-http-port
        - name: HTTPS_PORT
          valueFrom:
            configMapKeyRef:
              name: configmap-mutlitool
              key: multitool-https-port
      volumes:
      - name: configmap-nginx-volume
        configMap:
          name: configmap-nginx-page
