apiVersion: v1
kind: Pod
metadata:
  name: multitool-dedic
  namespace: default
  labels:
    app: pod-multitool-dedic
spec:
  containers:
  - name: multitool
    image: wbitt/network-multitool
    ports:
    - containerPort: 80
      name: http
    - containerPort: 443
      name: https
