apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-multitool
spec:
  selector:
    app: nginx
  ports:
  - name: http-nginx
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https-nginx
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http-multitool
    port: 1180
    protocol: TCP
    targetPort: 1180
  - name: https-multitool
    port: 11443
    protocol: TCP
    targetPort: 11443